# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-21 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerDepot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Address', verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'db_table': 'producer_depots',
                'verbose_name': '\u0421\u043a\u043b\u0430\u0434 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u0421\u043a\u043b\u0430\u0434\u044b \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('barcode', models.CharField(max_length=64, verbose_name='\u0428\u0442\u0440\u0438\u0445-\u043a\u043e\u0434')),
                ('expiration_date', models.CharField(blank=True, default='', max_length=256, verbose_name='\u0421\u0440\u043e\u043a \u0433\u043e\u0434\u043d\u043e\u0441\u0442\u0438')),
                ('producer_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0426\u0435\u043d\u0430 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044f')),
                ('customer_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0426\u0435\u043d\u0430 \u0434\u043b\u044f \u0437\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430')),
                ('minimum_amount', models.IntegerField(default=1, verbose_name='\u041c\u0438\u043d\u0438\u043c\u0430\u043b\u044c\u043d\u043e\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('pack_amount', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432 \u0443\u043f\u0430\u043a\u043e\u0432\u043a\u0435')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='\u0412\u0435\u0441')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('length', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0414\u043b\u0438\u043d\u0430')),
                ('width', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430')),
                ('height', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0412\u044b\u0441\u043e\u0442\u0430')),
                ('description', models.TextField(blank=True, default='', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('expiration_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogs.ExpirationValue', verbose_name='\u0422\u0438\u043f \u0441\u0440\u043e\u043a\u0430 \u0433\u043e\u0434\u043d\u043e\u0441\u0442\u0438')),
                ('product_depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.ProducerDepot', verbose_name='\u0421\u043a\u043b\u0430\u0434')),
                ('seen', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u0422\u043e\u0432\u0430\u0440 \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u043d')),
            ],
            options={
                'db_table': 'product_cards',
                'verbose_name': '\u041a\u0430\u0440\u0442\u0430 \u0442\u043e\u0432\u0430\u0440\u0430',
                'verbose_name_plural': '\u041a\u0430\u0440\u0442\u044b \u0442\u043e\u0432\u0430\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0426\u0435\u043d\u0430')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0446\u0435\u043d\u044b')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.ProductCard', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442')),
            ],
            options={
                'db_table': 'product_prices',
                'verbose_name': '\u0426\u0435\u043d\u0430 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u0432',
            },
        ),
    ]
