# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20171004_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u0446\u0435\u043d\u044b'),
        ),
    ]
