# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0005_auto_20171005_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='barcode',
            field=models.CharField(max_length=64, verbose_name='\u0428\u0442\u0440\u0438\u0445-\u043a\u043e\u0434'),
        ),
    ]
