# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_auto_20171013_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
