# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_expirationvalue'),
        ('producer', '0008_auto_20171025_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='productcard',
            name='expiration_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='catalogs.ExpirationValue', verbose_name='\u0422\u0438\u043f \u0441\u0440\u043e\u043a\u0430 \u0433\u043e\u0434\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='height',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0412\u044b\u0441\u043e\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='length',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0414\u043b\u0438\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='productcard',
            name='width',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430'),
        ),
    ]
