# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0009_auto_20171026_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0421\u0440\u043e\u043a \u0433\u043e\u0434\u043d\u043e\u0441\u0442\u0438'),
        ),
    ]
