# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0010_auto_20171030_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
