# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0011_productcard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='expiration_date',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='\u0421\u0440\u043e\u043a \u0433\u043e\u0434\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='expiration_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogs.ExpirationValue', verbose_name='\u0422\u0438\u043f \u0441\u0440\u043e\u043a\u0430 \u0433\u043e\u0434\u043d\u043e\u0441\u0442\u0438'),
        ),
    ]
