# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='order_payments', verbose_name='\u041f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0435 \u043f\u043e\u0440\u0443\u0447\u0435\u043d\u0438\u0435')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0440\u0443\u0447\u0435\u043d\u0438\u044f')),
            ],
            options={
                'db_table': 'direct_payment',
                'verbose_name': '\u041f\u0440\u044f\u043c\u043e\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434 \u043d\u0430 \u0440\u0430\u0441\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442',
                'verbose_name_plural': '\u041f\u0440\u044f\u043c\u044b\u0435 \u043f\u0435\u0440\u0435\u0432\u043e\u0434\u044b \u043d\u0430 \u0440\u0430\u0441\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u0435\u043d\u0435\u0433 \u0437\u0430 \u0437\u0430\u043a\u0430\u0437')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
            ],
            options={
                'db_table': 'order_payments',
                'verbose_name': '\u041f\u043b\u0430\u0442\u0451\u0436 \u043f\u043e \u0437\u0430\u043a\u0430\u0437\u0443',
                'verbose_name_plural': '\u041f\u043b\u0430\u0442\u0435\u0436\u0438 \u043f\u043e \u0437\u0430\u043a\u0430\u0437\u0430\u043c',
            },
        ),
        migrations.AddField(
            model_name='directpayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.OrderPayment', verbose_name='\u043f\u043b\u0430\u0442\u0451\u0436\u043d\u0430\u044f \u0441\u0443\u0449\u043d\u043e\u0441\u0442\u044c'),
        ),
    ]
