# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-08 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='order_payments', verbose_name='\u041f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0435 \u043f\u043e\u0440\u0443\u0447\u0435\u043d\u0438\u0435')),
                ('document_id', models.DecimalField(decimal_places=0, default=None, max_digits=20, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0433\u043e \u043f\u043e\u0440\u0443\u0447\u0435\u043d\u0438\u044f')),
                ('date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0440\u0443\u0447\u0435\u043d\u0438\u044f')),
            ],
            options={
                'db_table': 'direct_payment',
                'verbose_name': '\u041f\u0440\u044f\u043c\u043e\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434 \u043d\u0430 \u0440\u0430\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442',
                'verbose_name_plural': '\u041f\u0440\u044f\u043c\u044b\u0435 \u043f\u0435\u0440\u0435\u0432\u043e\u0434\u044b \u043d\u0430 \u0440\u0430\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442',
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='\u0422\u0435\u043b\u043e \u043e\u0442\u0432\u0435\u0442\u0430')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
            ],
            options={
                'db_table': 'failure_redirect',
                'verbose_name': 'Failure redirect \u0441\u0438\u0441\u0442\u0435\u043c\u044b paymaster',
                'verbose_name_plural': 'Failure redirect \u0441\u0438\u0441\u0442\u0435\u043c\u044b paymaster',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0426\u0435\u043d\u0430')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('type', models.IntegerField(choices=[(0, '\u041e\u043f\u043b\u0430\u0442\u0430 \u0440\u0430\u0441\u0447\u0451\u0442\u043d\u043e\u0433\u043e \u0441\u0447\u0451\u0442\u0430'), (1, '\u041e\u043f\u043b\u0430\u0442\u0430 \u043a\u0430\u0440\u0442\u043e\u0439')], default=None, null=True, verbose_name='\u0422\u0438\u043f \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
            ],
            options={
                'db_table': 'order_payments',
                'verbose_name': '\u041f\u043b\u0430\u0442\u0451\u0436 \u043f\u043e \u0437\u0430\u043a\u0430\u0437\u0443',
                'verbose_name_plural': '\u041f\u043b\u0430\u0442\u0435\u0436\u0438 \u043f\u043e \u0437\u0430\u043a\u0430\u0437\u0430\u043c',
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='\u0422\u0435\u043b\u043e \u043e\u0442\u0432\u0435\u0442\u0430')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
            ],
            options={
                'db_table': 'payment_notification',
                'verbose_name': 'Payment notification \u0441\u0438\u0441\u0442\u0435\u043c\u044b paymaster',
                'verbose_name_plural': 'Payment notifications \u0441\u0438\u0441\u0442\u0435\u043c\u044b paymaster',
            },
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(verbose_name='\u0422\u0435\u043b\u043e \u043e\u0442\u0432\u0435\u0442\u0430')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
            ],
            options={
                'db_table': 'success_redirect',
                'verbose_name': 'Success redirect \u0441\u0438\u0441\u0442\u0435\u043c\u044b paymaster',
                'verbose_name_plural': 'Success redirect \u0441\u0438\u0441\u0442\u0435\u043c\u044b paymaster',
            },
        ),
        migrations.AddField(
            model_name='directpayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.OrderPayment', verbose_name='\u041f\u043b\u0430\u0442\u0451\u0436\u043d\u0430\u044f \u0441\u0443\u0449\u043d\u043e\u0441\u0442\u044c'),
        ),
    ]
