# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpayment',
            old_name='amount',
            new_name='price',
        ),
    ]
