# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20171206_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
