# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_orderpayment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='type',
            field=models.IntegerField(choices=[(0, '\u041e\u043f\u043b\u0430\u0442\u0430 \u0440\u0430\u0441\u0441\u0447\u0451\u0442\u043d\u043e\u0433\u043e \u0441\u0447\u0451\u0442\u0430'), (1, '\u041e\u043f\u043b\u0430\u0442\u0430 \u043a\u0430\u0440\u0442\u043e\u0439')], default=0, verbose_name='\u0422\u0438\u043f \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
    ]
