# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_failure_paymentnotification_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directpayment',
            options={'verbose_name': '\u041f\u0440\u044f\u043c\u043e\u0439 \u043f\u0435\u0440\u0435\u0432\u043e\u0434 \u043d\u0430 \u0440\u0430\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442', 'verbose_name_plural': '\u041f\u0440\u044f\u043c\u044b\u0435 \u043f\u0435\u0440\u0435\u0432\u043e\u0434\u044b \u043d\u0430 \u0440\u0430\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442'},
        ),
        migrations.AlterField(
            model_name='failure',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='type',
            field=models.IntegerField(choices=[(0, '\u041e\u043f\u043b\u0430\u0442\u0430 \u0440\u0430\u0441\u0447\u0451\u0442\u043d\u043e\u0433\u043e \u0441\u0447\u0451\u0442\u0430'), (1, '\u041e\u043f\u043b\u0430\u0442\u0430 \u043a\u0430\u0440\u0442\u043e\u0439')], default=None, null=True, verbose_name='\u0422\u0438\u043f \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='success',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
    ]
