# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u0418\u043d\u0434\u0435\u043a\u0441')),
                ('region', models.CharField(max_length=40, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('city', models.CharField(max_length=80, verbose_name='\u0413\u043e\u0440\u043e\u0434/\u041d\u0430\u0441\u0435\u043b\u0451\u043d\u043d\u044b\u0439 \u043f\u0443\u043d\u043a\u0442')),
                ('street', models.CharField(max_length=80, verbose_name='\u0423\u043b\u0438\u0446\u0430')),
                ('house', models.CharField(max_length=100, verbose_name='\u0414\u043e\u043c')),
                ('block', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041a\u043e\u0440\u043f\u0443\u0441')),
                ('structure', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435')),
                ('flat', models.CharField(max_length=20, verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430/\u041e\u0444\u0438\u0441')),
            ],
            options={
                'db_table': 'address',
                'verbose_name': '\u0410\u0434\u0440\u0435\u0441',
                'verbose_name_plural': '\u0410\u0434\u0440\u0435\u0441\u0430',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='\u0418\u041d\u041d')),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True, verbose_name='\u041e\u0413\u0420\u041d')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='\u041a\u041f\u041f')),
                ('physical_is_juridical', models.BooleanField(default=False, verbose_name='\u0421\u043e\u0432\u043f\u0430\u0434\u0430\u0435\u0442 \u0441 \u044e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u043c')),
                ('juridical_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juridical_profile', to='core.Address', verbose_name='\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0430\u0434\u0440\u0435\u0441')),
                ('physical_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_profile', to='core.Address', verbose_name='\u0424\u0438\u0437\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0430\u0434\u0440\u0435\u0441')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'db_table': 'user_profile',
                'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439',
            },
        ),
    ]
