# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-08 20:17
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, verbose_name='\u0420\u0430\u0441\u0447\u0451\u0442\u043d\u044b\u0439 \u0441\u0447\u0451\u0442')),
                ('bik', models.CharField(max_length=9, verbose_name='\u0411\u0418\u041a')),
                ('bank_name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u0431\u0430\u043d\u043a\u0430')),
                ('correspondent_account', models.CharField(max_length=20, verbose_name='\u041a\u043e\u0440\u0440\u0435\u0441\u043f\u043e\u043d\u0434\u0435\u043d\u0442\u0441\u043a\u0438\u0439 \u0441\u0447\u0435\u0442')),
            ],
            options={
                'db_table': 'account',
                'verbose_name': '\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u043c\u044b\u0439 \u0441\u0447\u0451\u0442',
                'verbose_name_plural': '\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u043c\u044b\u0435 \u0441\u0447\u0435\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=6, null=True, verbose_name='\u0418\u043d\u0434\u0435\u043a\u0441')),
                ('region', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('city', models.CharField(max_length=80, verbose_name='\u0413\u043e\u0440\u043e\u0434/\u041d\u0430\u0441\u0435\u043b\u0451\u043d\u043d\u044b\u0439 \u043f\u0443\u043d\u043a\u0442')),
                ('street', models.CharField(max_length=80, verbose_name='\u0423\u043b\u0438\u0446\u0430')),
                ('house', models.CharField(max_length=100, verbose_name='\u0414\u043e\u043c')),
                ('block', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041a\u043e\u0440\u043f\u0443\u0441')),
                ('structure', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435')),
                ('flat', models.CharField(blank=True, default='', max_length=20, verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430/\u041e\u0444\u0438\u0441')),
                ('full_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441')),
            ],
            options={
                'db_table': 'address',
                'verbose_name': '\u0410\u0434\u0440\u0435\u0441',
                'verbose_name_plural': '\u0410\u0434\u0440\u0435\u0441\u0430',
            },
        ),
        migrations.CreateModel(
            name='ComplexTerritory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'territory_complex',
                'verbose_name': '\u041c\u043d\u043e\u0433\u043e\u0443\u0433\u043e\u043b\u044c\u043d\u044b\u0435 \u0442\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u0438',
                'verbose_name_plural': '\u041c\u043d\u043e\u0433\u043e\u0443\u0433\u043e\u043b\u044c\u043d\u044b\u0435 \u0442\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, verbose_name='\u0421\u0435\u0440\u0438\u044f')),
                ('number', models.CharField(max_length=6, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('issued_by', models.CharField(max_length=256, verbose_name='\u041a\u0435\u043c \u0432\u044b\u0434\u0430\u043d')),
                ('issued_date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u0434\u0430\u0447\u0438')),
                ('document', models.FileField(upload_to='identity_documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442, \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0430\u044e\u0449\u0438\u0439 \u043f\u0440\u0430\u0432\u043e \u043f\u043e\u0434\u043f\u0438\u0441\u0438')),
            ],
            options={
                'db_table': 'identity_documents',
                'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442, \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0430\u044e\u0449\u0438\u0439 \u043b\u0438\u0447\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b, \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0430\u044e\u0449\u0438\u0435 \u043b\u0438\u0447\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='LegalAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'legal_acts',
                'verbose_name': '\u041f\u0440\u0430\u0432\u043e\u0432\u043e\u0439 \u0430\u043a\u0442',
                'verbose_name_plural': '\u041f\u0440\u0430\u0432\u043e\u0432\u044b\u0435 \u0430\u043a\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('full_name', models.CharField(max_length=80, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'organization_types',
                'verbose_name': '\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u043e\u043d\u043d\u043e-\u043f\u0440\u0430\u0432\u043e\u0432\u0430\u044f \u0444\u043e\u0440\u043c\u0430',
                'verbose_name_plural': '\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u043e\u043d\u043d\u043e-\u043f\u0440\u0430\u0432\u043e\u0432\u044b\u0435 \u0444\u043e\u0440\u043c\u044b',
            },
        ),
        migrations.CreateModel(
            name='SignerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('name', models.CharField(max_length=40, verbose_name='\u0418\u043c\u044f')),
                ('patronymic', models.CharField(max_length=40, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('birth_date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('position', models.CharField(max_length=60, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'db_table': 'signer_info',
                'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u0430',
                'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', '\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'), ('producer', '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'), ('manager', ' \u0422\u043e\u0440\u0433\u043e\u0432\u044b\u0439 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c'), ('supervisor', '\u0421\u0443\u043f\u0435\u0440\u0432\u0438\u0437\u043e\u0440 \u0432\u0441\u0435\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u044b')], max_length=20, verbose_name='\u0420\u043e\u043b\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438')),
                ('phone', models.CharField(max_length=15, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='\u0418\u041d\u041d')),
                ('ogrn', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u041e\u0413\u0420\u041d')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='\u041a\u041f\u041f')),
                ('physical_is_juridical', models.BooleanField(default=False, verbose_name='\u0421\u043e\u0432\u043f\u0430\u0434\u0430\u0435\u0442 \u0441 \u044e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u043c')),
                ('created', models.BooleanField(default=False, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0444\u0438\u043b\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043e \u0438\u043b\u0438 \u043f\u0440\u043e\u043f\u0443\u0449\u0435\u043d\u043e')),
                ('identity_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.IdentityDocument', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442')),
                ('juridical_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juridical_profile', to='core.Address', verbose_name='\u042e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0430\u0434\u0440\u0435\u0441')),
                ('legal_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LegalAct', verbose_name='\u041f\u0440\u0430\u0432\u043e\u0432\u043e\u0439 \u0430\u043a\u0442')),
                ('organization_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OrganizationType', verbose_name='\u041e\u0440\u0433\u0430\u043d\u0438\u0437\u0430\u0446\u0438\u043e\u043d\u043d\u043e \u043f\u0440\u0430\u0432\u043e\u0432\u0430\u044f \u0444\u043e\u0440\u043c\u0430')),
                ('physical_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_profile', to='core.Address', verbose_name='\u0424\u0438\u0437\u0438\u0447\u0435\u0441\u043a\u0438\u0439 \u0430\u0434\u0440\u0435\u0441')),
                ('signer_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signer_info', to='core.SignerInfo', verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u0430')),
            ],
            options={
                'db_table': 'user_profile',
                'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f',
                'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439',
            },
        ),
        migrations.CreateModel(
            name='SophisticatedUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.SophisticatedUser', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='complexterritory',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0422\u043e\u0440\u0433\u043e\u0432\u044b\u0439 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile', verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c'),
        ),
    ]
