# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170928_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signer_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signer_info', to='core.SignerInfo', verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u043f\u043e\u0434\u043f\u0438\u0441\u0430\u043d\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='legalact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
