# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171002_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, verbose_name='\u0421\u0435\u0440\u0438\u044f')),
                ('number', models.CharField(max_length=6, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('issued_by', models.CharField(max_length=256, verbose_name='\u041a\u0435\u043c \u0432\u044b\u0434\u0430\u043d')),
                ('issued_date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u0434\u0430\u0447\u0438')),
                ('document', models.FileField(upload_to='identity_documents', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442, \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0430\u044e\u0449\u0438\u0439 \u043f\u0440\u0430\u0432\u043e \u043f\u043e\u0434\u043f\u0438\u0441\u0438')),
            ],
            options={
                'db_table': 'identity_documents',
                'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442, \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0430\u044e\u0449\u0438\u0439 \u043b\u0438\u0447\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b, \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0430\u044e\u0449\u0438\u0435 \u043b\u0438\u0447\u043d\u043e\u0441\u0442\u044c',
            },
        ),
    ]
