# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_identitydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.IdentityDocument', verbose_name='\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442'),
        ),
    ]
