# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0430\u0434\u0440\u0435\u0441'),
        ),
    ]
