# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_address_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.BooleanField(default=False, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u0438\u0435 \u043f\u0440\u043e\u0444\u0438\u043b\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043e \u0438\u043b\u0438 \u043f\u0440\u043e\u043f\u0443\u0449\u0435\u043d\u043e'),
        ),
    ]
