# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171116_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430/\u041e\u0444\u0438\u0441'),
        ),
    ]
