# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171121_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signerinfo',
            name='inn',
        ),
    ]
