# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_signerinfo_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u041e\u0413\u0420\u041d'),
        ),
    ]
