# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 14:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171123_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326, verbose_name='\u0428\u0438\u0440\u043e\u0442\u0430\\\u0434\u043e\u043b\u0433\u043e\u0442\u0430'),
        ),
    ]
