# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180214_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='name',
            field=models.CharField(default='enter territory name', max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
