# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 08:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180222_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Territory',
        ),
        migrations.AlterField(
            model_name='complexterritory',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=4326, verbose_name='\u041c\u043d\u043e\u0433\u043e\u0443\u0433\u043e\u043b\u044c\u043d\u0430\u044f \u0441\u0443\u0449\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='complexterritory',
            name='representative',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0422\u043e\u0440\u0433\u043e\u0432\u044b\u0439 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c'),
            preserve_default=False,
        ),
    ]
