# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180301_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexterritory',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SophisticatedUser', verbose_name='\u0422\u043e\u0440\u0433\u043e\u0432\u044b\u0439 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
