# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180305_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexterritory',
            name='polygon',
        ),
    ]
