# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_complexterritory_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', '\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'), ('producer', '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'), ('manager', ' \u0422\u043e\u0440\u0433\u043e\u0432\u044b\u0439 \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u044c'), ('supervisor', '\u0421\u0443\u043f\u0435\u0440\u0432\u0438\u0437\u043e\u0440 \u0432\u0441\u0435\u044f \u0441\u0438\u0441\u0442\u0435\u043c\u044b')], default='supervisor', max_length=20, verbose_name='\u0420\u043e\u043b\u044c \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
            preserve_default=False,
        ),
    ]
