# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-08 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('producer', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('order_status', models.IntegerField(choices=[(1, '\u041d\u0435 \u043e\u043f\u043b\u0430\u0447\u0435\u043d'), (2, '\u0421\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d'), (3, '\u041d\u0435 \u0441\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d'), (4, '\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d'), (5, '\u041e\u0442\u043c\u0435\u043d\u0451\u043d'), (6, '\u0412 \u043f\u0443\u0442\u0438'), (7, '\u0414\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d'), (8, '\u0418\u0441\u043f\u043e\u043b\u043d\u0435\u043d')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.OrderPayment', verbose_name='\u041f\u043b\u0430\u0442\u0451\u0436\u043d\u0430\u044f \u0441\u0443\u0449\u043d\u043e\u0441\u0442\u044c')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='core.SophisticatedUser', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a')),
            ],
            options={
                'db_table': 'orders',
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='\u0426\u0435\u043d\u0430 \u043d\u0430 \u043c\u043e\u043c\u0435\u043d\u0442 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_unit', to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Order', verbose_name='\u0417\u0430\u043a\u0430\u0437')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_unit', to='core.SophisticatedUser', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.ProductCard', verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u0437\u0430\u043a\u0430\u0437\u0430')),
            ],
            options={
                'db_table': 'order_units',
                'verbose_name': '\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u0437\u0430\u043a\u0430\u0437\u0430',
                'verbose_name_plural': '\u041f\u043e\u0437\u0438\u0446\u0438\u0438 \u0437\u0430\u043a\u0430\u0437\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Address', verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradepoint', to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a')),
                ('territory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ComplexTerritory', verbose_name='\u0422\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u044f')),
            ],
            options={
                'db_table': 'trade_points',
                'verbose_name': '\u0422\u043e\u0440\u0433\u043e\u0432\u0430\u044f \u0442\u043e\u0447\u043a\u0430',
                'verbose_name_plural': '\u0422\u043e\u0440\u0433\u043e\u0432\u044b\u0435 \u0442\u043e\u0447\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='trade_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.TradePoint', verbose_name='\u0422\u043e\u0440\u0433\u043e\u0432\u0430\u044f \u0442\u043e\u0447\u043a\u0430'),
        ),
    ]
