# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0010_auto_20171030_0918'),
        ('customer', '0010_auto_20171005_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'order_statuses',
                'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u044f\u0432\u043a\u0438',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u044b \u0437\u0430\u044f\u0432\u043e\u043a',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.TradePoint', verbose_name='\u0422\u043e\u0440\u0433\u043e\u0432\u0430\u044f \u0442\u043e\u0447\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='tradepoint',
            name='name',
            field=models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterUniqueTogether(
            name='orderunit',
            unique_together=set([('order', 'product')]),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.OrderStatuses', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
    ]
