# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20171108_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trade_point',
        ),
        migrations.AddField(
            model_name='orderunit',
            name='trade_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.TradePoint', verbose_name='\u0422\u043e\u0440\u0433\u043e\u0432\u0430\u044f \u0442\u043e\u0447\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.OrderStatuses', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.ProductCard', verbose_name='\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
