# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20171108_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
    ]
