# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0013_orderunit_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
            preserve_default=False,
        ),
    ]
