# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20171116_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderunit',
            name='trade_point',
        ),
    ]
