# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0018_auto_20171120_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, '\u041d\u0430 \u0441\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d\u0438\u0438'), (2, '\u0421\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d'), (3, '\u041d\u0435 \u0441\u043e\u0433\u043b\u0430\u0441\u043e\u0432\u0430\u043d'), (4, '\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d'), (5, '\u041e\u0442\u043c\u0435\u043d\u0451\u043d'), (6, '\u0412 \u043f\u0443\u0442\u0438'), (7, '\u0414\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d'), (8, '\u0418\u0441\u043f\u043e\u043b\u043d\u0435\u043d')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u044f\u0432\u043a\u0438'),
        ),
    ]
