# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0019_auto_20171123_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_unit', to=settings.AUTH_USER_MODEL, verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Order', verbose_name='\u0417\u0430\u043a\u0430\u0437'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_unit', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
        ),
    ]
