# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('customer', '0021_auto_20171124_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatuses',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payments.OrderPayment', verbose_name='\u041f\u043b\u0430\u0442\u0451\u0436\u043d\u0430\u044f \u0441\u0443\u0449\u043d\u043e\u0441\u0442\u044c'),
            preserve_default=False,
        ),
    ]
