# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20171206_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderunit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='\u0426\u0435\u043d\u0430 \u043d\u0430 \u043c\u043e\u043c\u0435\u043d\u0442 \u0437\u0430\u043a\u0430\u0437\u0430'),
            preserve_default=False,
        ),
    ]
