# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20180301_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderunit',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_unit', to='core.SophisticatedUser', verbose_name='\u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a'),
        ),
    ]
