# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_auto_20180305_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepoint',
            name='name',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
