# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpirationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'expiration_values',
                'verbose_name': '\u0412\u0438\u0434 \u0441\u0440\u043e\u043a\u0430 \u0433\u043e\u0434\u043d\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u0412\u0438\u0434\u044b \u0441\u0440\u043e\u043a\u043e\u0432 \u0433\u043e\u0434\u043d\u043e\u0441\u0442\u0438',
            },
        ),
    ]
