# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_expirationvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0435\u0430\u043a\u0442\u0438\u0432\u043d\u0430\u044f'),
        ),
    ]
