# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_category_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'territory',
                'verbose_name': '\u0422\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u0422\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u0438',
            },
        ),
    ]
