# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_territory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Territory',
        ),
    ]
